version: "3.9"
services:
  api:
    build: ./api
    container_name: "api"
    tty: true
    stdin_open: true
    volumes:
      - ./api:/api
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
